### PR TITLE
fix(Autoprefixer): Update the Autoprefixer configuration

### PR DESCRIPTION
**Pull request by georgespyropoulos**
Updating the configuration to match the latest browser support policy.

### CODE REVIEW

**Review by mengtzu — APPROVED** [review]
Other than the $compile thingy, weird.

**Review by markdalgleish — CHANGES_REQUESTED** [review]
This needs to be marked as a patch or a fix, not a chore.

**Comment by georgespyropoulos** [comment]
@markdalgleish have changed the title, does that look ok?

**Review by mattcompiles — APPROVED** [review]
Looks good

**Review by markdalgleish — APPROVED** [review]

**Pull request merged**
